version: '3'
services:
  cms-service.maxmastalerz.com-private:
    build:
      context: ./strapi/
      dockerfile: Dockerfile.prod
    environment:
     - PROTOCOL=${PROTOCOL}
     - BASE_URL=${BASE_URL}
     - NODE_ENV=production
     - HOST=${STRAPI_HOST}
     - PORT=${STRAPI_INTERNAL_PORT}
     - JWT_SECRET=${STRAPI_JWT_SECRET}
     - ADMIN_JWT_SECRET={STRAPI_ADMIN_JWT_SECRET}
     - MYSQL_HOST=${MYSQL_HOST}
     - MYSQL_PORT=${MYSQL_PORT}
     - MYSQL_DATABASE=${MYSQL_DATABASE}
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - AWS_SES_KEY=${STRAPI_AWS_SES_USER_KEY}
     - AWS_SES_SECRET=${STRAPI_AWS_SES_USER_SECRET}
     - AWS_S3_REGION=${STRAPI_AWS_S3_REGION}
     - AWS_S3_BUCKET=${STRAPI_AWS_S3_BUCKET}
     - AWS_S3_KEY=${STRAPI_AWS_S3_KEY}
     - AWS_S3_SECRET=${STRAPI_AWS_S3_SECRET}
     - AWS_CLOUDFRONT=${STRAPI_AWS_CLOUDFRONT}
     - HCAPTCHA_SECRET_KEY=${STRAPI_HCAPTCHA_SECRET_KEY}

  #
  # REMEMBER: Gatsby doesn't run in docker in production. It runs in Netlify
  #
  gatsby-service.maxmastalerz.com-private:
    build:
      context: ./gatsby/
      dockerfile: Dockerfile.preprod
    depends_on:
      - cms-service.maxmastalerz.com-private
    #NOTE: OS Environment variables that start with GATSBY_ will also be available in browser javascript.
    environment:
     - HOST=${GATSBY_HOST}
     - PORT=${GATSBY_PORT}
     - GATSBY_PROTOCOL=${PROTOCOL}
     - GATSBY_BASE_URL=${BASE_URL}
     - GATSBY_HCAPTCHA_SITE_KEY=${GATSBY_HCAPTCHA_SITE_KEY}
     - NODE_ENV=production
     - STRAPI_SERVICE_HOSTNAME=${STRAPI_SERVICE_HOSTNAME}
     - STRAPI_INTERNAL_PORT=${STRAPI_INTERNAL_PORT}






  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile.preprod
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    environment:
      - PROTOCOL=${PROTOCOL}
      - BASE_URL=${BASE_URL}
      - NGINX_PORT=${NGINX_PORT}
      - GATSBY_PORT=${GATSBY_PORT}
      - STRAPI_INTERNAL_PORT=${STRAPI_INTERNAL_PORT}
      - REMARK42_PORT=${REMARK42_PORT}
      - GATSBY_SERVICE_HOSTNAME=${GATSBY_SERVICE_HOSTNAME}
      - STRAPI_SERVICE_HOSTNAME=${STRAPI_SERVICE_HOSTNAME}
      - REMARK42_SERVICE_HOSTNAME=${REMARK42_SERVICE_HOSTNAME}
    depends_on:
      - cms-service.maxmastalerz.com-private
      - gatsby-service.maxmastalerz.com-private

  remark42-service.maxmastalerz.com-private:
      image: umputun/remark42:latest
      restart: always
      environment:
          - REMARK_PORT=${REMARK42_PORT}
          - REMARK_URL=${PROTOCOL}remark42.${BASE_URL}  # url pointing to your remark42 server
          - SITE=${REMARK42_SITE_ID}                     # site ID, same as used for `site_id`, see "Setup on your website"
          - SECRET=${REMARK42_SECRET}           # secret key
          - AUTH_GITHUB_CID=${REMARK42_GITHUB_OAUTH_CLIENT_ID}           # oauth2 client ID
          - AUTH_GITHUB_CSEC=${REMARK42_GITHUB_OAUTH_CLIENT_SECRET}      # oauth2 client secret
          - AUTH_ANON=true
          - ANON_VOTE=true
          - ADMIN_SHARED_ID=github_ce2d4e381aa49ffbf800f7d6527e2b774a1be617
      volumes:
          - remark42:/srv/var                        # persistent volume to store all remark42 data

volumes:
  remark42: