version: '3'
services:
  cms-service.maxmastalerz.com-private:
    build:
      context: ./strapi/
      dockerfile: Dockerfile.dev
    environment:
     - PROTOCOL=${PROTOCOL}
     - BASE_URL=${BASE_URL}
     - HOST=${STRAPI_HOST}
     - PORT=${STRAPI_INTERNAL_PORT}
     - JWT_SECRET=${STRAPI_JWT_SECRET}
     - ADMIN_JWT_SECRET={STRAPI_ADMIN_JWT_SECRET}
     - MYSQL_HOST=${MYSQL_HOST}
     - MYSQL_PORT=${MYSQL_PORT}
     - MYSQL_DATABASE=${MYSQL_DATABASE}
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - AWS_SES_KEY=${STRAPI_AWS_SES_USER_KEY}
     - AWS_SES_SECRET=${STRAPI_AWS_SES_USER_SECRET}
     - HCAPTCHA_SECRET_KEY=${STRAPI_HCAPTCHA_SECRET_KEY}
    volumes:
      - ./strapi:/strapi-app
      - strapi_node_modules:/strapi-app/node_modules/
    depends_on:
      - db

  gatsby-service.maxmastalerz.com-private:
    build:
      context: ./gatsby/
      dockerfile: Dockerfile.dev
    #These ports are only exposed in dev for testing gatsby directly if we wish to(Rather than going thru nginx)
    #DO NOT expose this in the prod compose file.
    ports:
      - ${GATSBY_PORT}:${GATSBY_PORT}
    volumes:
      - ./gatsby:/gatsby-app
      - gatsby_node_modules:/gatsby-app/node_modules/
    depends_on:
      - cms-service.maxmastalerz.com-private
    #NOTE: OS Environment variables that start with GATSBY_ will be available in browser javascript.
    environment:
     - HOST=${GATSBY_HOST}
     - PORT=${GATSBY_PORT}
     - GATSBY_PROTOCOL=${PROTOCOL}
     - GATSBY_BASE_URL=${BASE_URL}
     - GATSBY_HCAPTCHA_SITE_KEY=${GATSBY_HCAPTCHA_SITE_KEY}
     - STRAPI_SERVICE_HOSTNAME=${STRAPI_SERVICE_HOSTNAME}
     - STRAPI_INTERNAL_PORT=${STRAPI_INTERNAL_PORT}
     - ENABLE_GATSBY_REFRESH_ENDPOINT=true
     - NODE_ENV=development
     - INTERNAL_STATUS_PORT=${GATSBY_INTERNAL_STATUS_PORT}

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile.dev
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
      - ${GATSBY_INTERNAL_STATUS_PORT}:${GATSBY_INTERNAL_STATUS_PORT}
    environment:
      - PROTOCOL=${PROTOCOL}
      - BASE_URL=${BASE_URL}
      - NGINX_PORT=${NGINX_PORT}
      - GATSBY_INTERNAL_STATUS_PORT=${GATSBY_INTERNAL_STATUS_PORT}
      - GATSBY_PORT=${GATSBY_PORT}
      - STRAPI_INTERNAL_PORT=${STRAPI_INTERNAL_PORT}
      - REMARK42_PORT=${REMARK42_PORT}
      - GATSBY_SERVICE_HOSTNAME=${GATSBY_SERVICE_HOSTNAME}
      - STRAPI_SERVICE_HOSTNAME=${STRAPI_SERVICE_HOSTNAME}
      - REMARK42_SERVICE_HOSTNAME=${REMARK42_SERVICE_HOSTNAME}
    depends_on:
      - cms-service.maxmastalerz.com-private
      - gatsby-service.maxmastalerz.com-private

  db:
    build:
      context: ./db/
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE - stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log
    ports:
      - 3306:3306 # [OPTIONAL] Ports are only here so we can connect to the db via mysql workbench(or similar) when dev'ing.

  remark42-service.maxmastalerz.com-private:
      image: umputun/remark42:latest
      restart: always
      environment:
          - REMARK_PORT=${REMARK42_PORT}
          - REMARK_URL=${PROTOCOL}remark42.${BASE_URL}  # url pointing to your remark42 server
          - SITE=${REMARK42_SITE_ID}                     # site ID, same as used for `site_id`, see "Setup on your website"
          - SECRET=${REMARK42_SECRET}           # secret key
          - AUTH_GITHUB_CID=${REMARK42_GITHUB_OAUTH_CLIENT_ID}           # oauth2 client ID
          - AUTH_GITHUB_CSEC=${REMARK42_GITHUB_OAUTH_CLIENT_SECRET}      # oauth2 client secret
          - AUTH_ANON=true
          - ANON_VOTE=true
          - ADMIN_SHARED_ID=github_ce2d4e381aa49ffbf800f7d6527e2b774a1be617
      volumes:
          - remark42:/srv/var                        # persistent volume to store all remark42 data

volumes:
  db:
  strapi_node_modules:
  gatsby_node_modules:
  remark42: