FROM node:12

WORKDIR /gatsby-app

RUN npm install -g gatsby-cli

COPY ./package.json .
RUN npm install
COPY . .

RUN ls -l

RUN apt-get -q update && apt-get -qy install netcat

RUN chmod +x ./wait-for

#Running npm run develop with -- passes on the paramters to the npm run scripts
CMD ["sh", "-c", "./wait-for -t 60 strapi:${STRAPI_PORT} -- npm run develop -- --host=${HOST} --port=${PORT}"]
