FROM node:12

WORKDIR /strapi-app

COPY ./package.json .
RUN npm install
COPY . .

RUN ls -l

RUN apt-get -q update && apt-get -qy install netcat

CMD ["./wait-for", "-t", "60", "db:3306", "--", "npm", "run", "develop"]