FROM node:12

ENV NODE_ENV=development
ENV ENV_PATH=.env.dev

WORKDIR /strapi-app

RUN apt-get -q update && apt-get -qy install netcat

COPY ./package.json .
RUN npm install
COPY . .

RUN ls -l

CMD ["./wait-for", "-t", "60", "db:3306", "--", "npm", "run", "develop"]