FROM node:12




#This NODE_ENV is required here to have strapi make the correct build. This env variable
#did not work when only passed from docker compose.
ENV NODE_ENV=production

WORKDIR /strapi-app

COPY ./package.json .
RUN npm install
COPY . .

RUN ls -l

RUN npm run build

CMD ["npm", "run", "start"]