FROM nginx:1.20.0
#Stable version

MAINTAINER Max Mastalerz <contact@maxmastalerz.com>

# Install packages
RUN apt-get update && apt-get -y install nginx-extras

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.preprod.conf /etc/nginx/nginx.conf

COPY preprod/templates /etc/nginx/templates
