FROM nginx:1.20.0
#Stable version

MAINTAINER Max Mastalerz <contact@maxmastalerz.com>

# Install packages
RUN apt-get update && apt-get -y install

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/nginx.conf

COPY prod/templates /etc/nginx/templates
